#!/usr/bin/env python3
"""Install ClawNote OpenClaw agents into a local OpenClaw workspace.

The script intentionally copies only project-owned templates and skills. It
does not read or write ~/.openclaw/openclaw.json, secrets, databases, logs, or
runtime memory files.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = PROJECT_ROOT / "config.json"
DEFAULT_AGENTS_DIR = Path.home() / ".openclaw" / "agents"
SAFE_AGENT_FILES = ("AGENTS.md", "SOUL.md", "IDENTITY.md")
RUNTIME_NAMES = {
    "HEARTBEAT.md",
    "USER.md",
    "TOOLS.md",
    "MEMORY.md",
    "openclaw-workspace-state.json",
    "memory",
    "archive",
    "__pycache__",
    ".pytest_cache",
    "node_modules",
}


def load_config() -> dict[str, Any]:
    with CONFIG_PATH.open(encoding="utf-8") as handle:
        config = json.load(handle)
    if not isinstance(config.get("agents"), list):
        raise ValueError("config.json must contain an agents list")
    return config


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install ClawNote agents and skills into ~/.openclaw/agents."
    )
    parser.add_argument(
        "--agents-dir",
        type=Path,
        default=DEFAULT_AGENTS_DIR,
        help="OpenClaw agents directory. Default: ~/.openclaw/agents",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned changes without writing files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace existing ClawNote agent folders after backing them up.",
    )
    parser.add_argument(
        "--verify-openclaw",
        action="store_true",
        help="Run openclaw skills info checks after installation when openclaw is available.",
    )
    return parser.parse_args()


def copytree_safe(source: Path, destination: Path) -> None:
    def ignore(_directory: str, names: list[str]) -> set[str]:
        return {name for name in names if name in RUNTIME_NAMES}

    shutil.copytree(source, destination, ignore=ignore)


def backup_existing(destination: Path, backup_root: Path, dry_run: bool) -> Path:
    backup_path = backup_root / destination.name
    if dry_run:
        return backup_path
    backup_root.mkdir(parents=True, exist_ok=True)
    shutil.move(str(destination), str(backup_path))
    return backup_path


def install_agent(
    agent: dict[str, Any],
    agents_dir: Path,
    backup_root: Path,
    *,
    dry_run: bool,
    force: bool,
) -> dict[str, Any]:
    agent_id = str(agent["id"])
    source = PROJECT_ROOT / str(agent["workspace"])
    destination = agents_dir / agent_id
    skills = list(agent.get("skills") or [])

    if not source.is_dir():
        raise FileNotFoundError(f"Agent workspace not found: {source}")

    result: dict[str, Any] = {
        "id": agent_id,
        "source": str(source.relative_to(PROJECT_ROOT)),
        "destination": str(destination),
        "skills": skills,
        "status": "installed",
        "backup": None,
    }

    if destination.exists():
        if not force:
            result["status"] = "skipped-existing"
            return result
        result["backup"] = str(backup_existing(destination, backup_root, dry_run))

    if dry_run:
        return result

    destination.mkdir(parents=True, exist_ok=True)
    for filename in SAFE_AGENT_FILES:
        source_file = source / filename
        if source_file.is_file():
            shutil.copy2(source_file, destination / filename)

    skills_source = source / "skills"
    if skills_source.is_dir():
        copytree_safe(skills_source, destination / "skills")

    manifest = {
        "project": "ClawNote",
        "agent_id": agent_id,
        "source_workspace": str(source.relative_to(PROJECT_ROOT)),
        "repo_path": str(PROJECT_ROOT),
        "skills": skills,
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "note": "Generated by scripts/setup_openclaw_local.py. No secrets are stored here.",
    }
    (destination / ".clawnote-install.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return result


def verify_openclaw(config: dict[str, Any]) -> list[dict[str, str]]:
    openclaw = shutil.which("openclaw")
    if not openclaw:
        return [{"status": "skipped", "message": "openclaw command not found in PATH"}]

    checks: list[dict[str, str]] = []
    for agent in config["agents"]:
        agent_id = str(agent["id"])
        for skill in agent.get("skills") or []:
            command = [openclaw, "skills", "info", str(skill), "--agent", agent_id]
            completed = subprocess.run(
                command,
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            checks.append(
                {
                    "agent": agent_id,
                    "skill": str(skill),
                    "status": "ok" if completed.returncode == 0 else "failed",
                    "message": completed.stdout.strip().splitlines()[-1]
                    if completed.stdout.strip()
                    else "",
                }
            )
    return checks


def main() -> int:
    args = parse_args()
    config = load_config()
    agents_dir = args.agents_dir.expanduser()
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_root = agents_dir / ".clawnote-backups" / timestamp

    print(f"ClawNote repo: {PROJECT_ROOT}")
    print(f"OpenClaw agents dir: {agents_dir}")
    if args.dry_run:
        print("Mode: dry-run")

    results = []
    for agent in config["agents"]:
        results.append(
            install_agent(
                agent,
                agents_dir,
                backup_root,
                dry_run=args.dry_run,
                force=args.force,
            )
        )

    print("\nAgent install plan/result:")
    for result in results:
        backup = f", backup={result['backup']}" if result.get("backup") else ""
        print(f"- {result['id']}: {result['status']} -> {result['destination']}{backup}")

    if args.verify_openclaw and not args.dry_run:
        print("\nOpenClaw verification:")
        for check in verify_openclaw(config):
            target = ""
            if "agent" in check:
                target = f"{check['agent']} / {check['skill']}: "
            print(f"- {target}{check['status']} {check['message']}".rstrip())

    skipped = [result["id"] for result in results if result["status"] == "skipped-existing"]
    if skipped:
        print("\nExisting agent folders were left unchanged:")
        print("- " + "\n- ".join(skipped))
        print("Run again with --force to back up and replace them.")

    print("\nNext steps:")
    print("1. Keep real credentials in ~/.openclaw/openclaw.json or environment variables.")
    print("2. Initialize ClawNote data with: python3 scripts/knowledge_db.py init")
    print("3. Start backend/frontend as described in README.md.")
    print("4. Optional check: python3 scripts/setup_openclaw_local.py --verify-openclaw")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
